version: '3.8'

services:
  kafori:
    image: kafori:v1.0
    container_name: kafori
    ports:
      - "10020:10020"
    volumes:
      - /opt/kafori/conf/settings.yaml:/opt/kafori/backend/settings.yaml
    restart: always