name: Build and push (tag)

on:
  push:
    tags:
      - '*'          # 可按需改为 v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Push and Export tar
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kafori-backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: |
            type=registry
            type=docker,dest=/tmp/kafori-backend.tar

      - name: GZip exported image
        run: |
          gzip -9 /tmp/kafori-backend.tar
          mv /tmp/kafori-backend.tar.gz kafori-backend-${{ github.ref_name }}.tar.gz
          echo "${{ steps.build.outputs.digest }}" > image-digest.txt
          echo "IMAGE_FILE=kafori-backend-${{ github.ref_name }}.tar.gz" >> $GITHUB_ENV

      - name: Upload image tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: kafori-backend-${{ github.ref_name }}.tar.gz
            # 已 gzip，关闭再次压缩
          path: ${{ env.IMAGE_FILE }}
          compression-level: 0
          retention-days: 7

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: image-digest-${{ github.ref_name }}
          path: image-digest.txt
          retention-days: 30