name: Build and push (tag)

on:
  push:
    tags:
      - '*'          # 如只想语义版本，用 v* 或 v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kafori-backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max