name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lzma development library
        run: sudo apt-get update && sudo apt-get install -y liblzma-dev

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: kafori
          environment-file: kafori_conda.yml
          auto-activate-base: false

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Python dependencies with Poetry
        run: |
          poetry install --no-interaction --no-root

      - name: Run pytest
        run: |
          poetry run pytest -v --maxfail=2 --disable-warnings